name: Deploy Dashboard Web App to ACR

on:
  push:
    branches:
      - development
  workflow_dispatch:
    inputs:  
      environment:  
        type: environment  
        description: 'Environment to use'  
        default: 'development'  
        required: true  
      branch:  
        type: choice  
        description: 'Branch to use'  
        required: true  
        default: 'staging'  
        options:
          - development  
          - staging  
          - main  
      branch_override:  
        type: string  
        description: 'option to deploy a specific tag, branch, or feature'
        default: ''

jobs:
  DeployProd:
    name: Deploy to Buzz ${{ env.ENV_NAME }} by ${{ github.Actor }}
    environment:
      name: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.environment || github.ref_name }}
    runs-on: ubuntu-latest

    env:
      ENV_NAME: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.environment || github.ref_name }}
      AZURE_REPO: ${{ vars.BUZZ_REPO }}
      AZURE_REGISTRY_HOST: ${{ secrets.BUZZ_ECR_LOGINSERVER }}
      AZURE_REGISTRY_USER: ${{ secrets.BUZZ_ECR_USERNAME }}
      AZURE_REGISTRY_PW: ${{ secrets.BUZZ_ECR_PASSWORD }}

    steps:
      - name: Default - Checkout Repository
        if: ${{ github.event_name != 'workflow_dispatch' }}
        uses: actions/checkout@v4

      - name: Manual - Checkout Repository
        if: ${{ (github.event_name == 'workflow_dispatch') && (github.event.inputs.branch_override == '') }}
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Manual - Checkout Repository w/ Branch Override
        if: ${{ (github.event_name == 'workflow_dispatch') && (github.event.inputs.branch_override != '') }}
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch_override }}

      - name: Debug - Check Environment Vars
        run: |
          echo "DOCKER_ENVIRONMENT  ${{ vars.DOCKER_ENVIRONMENT }}"
          echo "BUZZ_REPO  ${{ env.AZURE_REPO }}"
      
      - name: Docker Login to ${{ env.ENV_NAME }}
        if: ${{ !always() }}
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.AZURE_REGISTRY_HOST }}
          username: ${{ env.AZURE_REGISTRY_USER }}
          password: ${{ env.AZURE_REGISTRY_PW }}
      
      - name: Build the Image and push to Container Registry in ${{ env.ENV_NAME }}
        if: ${{ !always() }}
        run: |
          docker build --build-arg ENVIRONMENT=${{ vars.DOCKER_ENVIRONMENT }} -t ${{ env.AZURE_REGISTRY_HOST }}/${{ env.AZURE_REPO }}:R${{ github.run_number }} -t ${{ env.AZURE_REGISTRY_HOST }}/${{ env.AZURE_REPO }}:latest .
          docker push ${{ env.AZURE_REGISTRY_HOST }}/${{ env.AZURE_REPO }}:latest