name: Manual Dispatch Test

on:
  workflow_dispatch:
    inputs:  
      environment:  
        type: environment  
        description: 'Environment to use'  
        default: 'development'  
        required: true  
      branch:  
        type: choice  
        description: 'Branch to use'  
        required: true  
        default: 'staging'  
        options:
          - development  
          - staging  
          - main  
      branch_override:  
        type: string  
        description: 'option to deploy a specific tag, branch, or feature'
        default: ''

jobs:
  test:
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.environment || github.ref_name }}
    steps:
      - name: Github Context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "Github event name ${{ github.event_name }} and ${{ github.event.inputs.environment }} and ${{ github.ref_name }}"
        run: echo "$GITHUB_CONTEXT"
      
      - name: Echo a secret
        run: echo "The secret is ${{ secrets.MY_SECRET }}"
      
      - name: Repo variable
        run: echo " Job name repo var ${{ vars.JOB_NAME }}"