name: Manual Dispatch Test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Echo a secret
        run: echo "The secret is ${{ secrets.MY_SECRET }}"
      
      - name: Repo variable
        run: echo " Job name repo var ${{ vars.JOB_NAME }}"